<div class="controls">
  <?= /** @var \Icinga\Module\Trapdirector\Controllers\ $this */ $this->tabs ?>
  <h1>Handlers</h1>
  <div class='action-bar'>
  </div>

<?= $this->qlink(
    $this->translate('Add a trap handler'),
    'trapdirector/handler/add',
    null,
    array(
        'class' => 'icon-plus',
        'title' => $this->translate('Create a new trap service')
    ))
?>  
 <br />  
 <?= $this->table->getPaginator(); ?> 

</div>


<div class="content">

<?= $this->table->render(); ?>

</div>
