<div class="controls">
  <?= /** @var \Icinga\Module\Trapdirector\Controllers\StatusController $this */ $this->tabs ?>
  <h1>Testing and debugging</h1>
</div>
<?php use Icinga\Web\Url; ?>
<div class="content">
  <h2>functions</h2>
  <form action="<?= Url::fromRequest() ?>" method="POST">
  		    input 1 : <input type="text" name="input1" > <br>
  		    input 2 : <input type="text" name="input2" > <br>
  		    input 3 : <input type="text" name="input3" > <br>
  		
  	<input type="submit" name = "submit" value="submit">
  </form>

   <br>
   Answer : <br>
   <pre><?= $this->answer?></pre>

</div>