<div class="controls">
  <?= /** @var \Icinga\Module\Trapdirector\Controllers\StatusController $this */ $this->tabs ?>
  <h1>Status and config of trap receivers</h1>
</div>

<div class="content">
  <h2>Database</h2>
  The current trap database contains : <br>
  <ul>
	<li> <span id="trap_count"><?= $this->trap_count ?> traps </span></li>
	<li> <span id="trap_object_count"><?= $this->trap_object_count ?> trap objects </span></li>
	<li> <span id="rule_count"><?= $this->rule_count ?> rules </span></li>
  </ul>
  Traps older than <input type="text" id="input_text_trap_days" maxlength="4" style="width:4em;"
  value="<?= $this->trap_days_delete ?>" /> days will be dropped.<br><br>
  <button type="button" id="button_trap_save" onclick='click_button_trap("save")'>Save</button>
  <button type="button" id="button_trap_doit" onclick='click_button_trap("execute")'>Do it now</button><br>

  <hr>
  
   <h2>Log destination</h2>
   Logs from the trap receiver will be sent to : <br>
	<select name="logsel" id="select_log_destination" >
<?php
		if (count($this->logDestinations)==0)
		{
			echo "<option value='-1'>Just shout loud</option>\n";
		}
		else
		{
			foreach ($this->logDestinations as $key => $val)
			{
				echo '<option value=' . $key;
				if ($val == $this->currentLogDestination)
				{
					echo ' selected ';
				}
				echo '>'.$val.'</option>'."\n";
			}
		}
?>		
	</select><br><br>
	For file log : <input type="text" id="input_current_log" maxlength="50"
	value="<?= $this->currentLogFile ?>" style="width=40em;"> <br><br>
	Log level : <select name="logsel" id="select_log_level" >
<?php
		if (count($this->logLevels)==0)
		{
			echo "<option value='-1'>Just shout loud</option>\n";
		}
		else
		{
			foreach ($this->logLevels as $key => $val)
			{
				echo '<option value=' . $key;
				if ($key == $this->currentLogLevel)
				{
					echo ' selected ';
				}
				echo '>'.$val.'</option>'."\n";
			}
		}
?>	
	</select><br><br>
	<button type="button" id="button_log_save" onclick='click_button_log()'>Save</button>
  
</div>

<script type='text/javascript'>
<?php use Icinga\Web\Url; ?>
dbHelper='<?= Url::fromPath("trapdirector/") ?>helper/dbmaintenance';
logHelper='<?= Url::fromPath("trapdirector/") ?>helper/logdestination';
// TODO : put function in a js (duplicate from add.phtml)
function displayWarning(message)
{
	$("#footer > #notifications").html('<li class="error fading-out">'+message+'</li>');
	//alert(message);
}
function displayOK(message)
{
	$("#footer > #notifications").html('<li class="success fading-out">'+message+'</li>');
}


function click_button_log()
{
	destination=$("#select_log_destination").val();
	file=$("#input_current_log").val();
	level=$("#select_log_level").val();
	$.ajax({
			url: logHelper,
			async: true,
			dataType: "json",
			type: "POST",
			data: 
			{
				"destination"	: 	destination,
				"file"			:	file,
				"level"			:	level
			},
	        success: function (data) 
			{
				//alert(data.status);
				if (data.status == "OK") 
				{
					displayOK("Done");
				} 
				else 
				{
					displayWarning("Error : "+data.status);		
				}
			},
			error: function (data)
			{
				displayWarning ("error" + data);
			}
	});	
}


function click_button_trap(action)
{
	days=$("#input_text_trap_days").val();
	$.ajax({
			url: dbHelper,
			async: true,
			dataType: "json",
			type: "POST",
			data: 
			{
				"action"	: 	action,
				"days"		:	days
			},
	        success: function (data) 
			{
				//alert(data.status);
				if (data.status == "OK") 
				{
					displayOK("Done");
				} 
				else 
				{
					displayWarning("Error : "+data.status);		
				}
			},
			error: function (data)
			{
				displayWarning ("error" + data);
			}
	});	
}

$(function() {
	return;
});

</script>