<div class="controls">
  <?= $tabs ?>
  <h1>Mib Management</h1>
</div>

<div class="content">
	<h2>MIB Database</h2>
	<ul>
	<li>Traps in database : <?= $this->mibDbCountTrap ?></li>
	<li>Objects in database : <?= $this->mibDbCount ?></li> 
	
	</ul>
	<br>
	<div id="id_animate_apply_mib2" ><i ></i></div>
	<button id="id_apply_mib" type="button" onclick="updateMIB()">
		<img id="id_animate_apply_mib" src="../../img/icons/refresh.png" style="display:none" ></a>
		Update MIB Database
	</button>  
	Note : can take several minutes
   <br>
   
   <h2>snmptranslate</h2>
  
  Binary (<?= $this->snmptranslate_bin ?>) : 
	<span style="background-color:<? 
		if ($this->snmptranslate_state == 'warn') echo "#FFE555";
		else echo "#00D500"
	?>; font-weight:bold;"> 
		<?= $this->snmptranslate ?> </span>
		
  <h2>Mib directories</h2>
  Directories where mibs are found (configured in module configuration) : 
  <ul>
<?php 
	//print_r($this->dirArray);
	foreach($this->dirArray as $key=>$dir) 
	{ 
		echo '<li>'.$dir.' : (aprox. '.exec('cat '.$dir.'/*  | grep "NOTIFICATION-TYPE" | wc -l 2>/dev/null');
		echo " traps defined)</li>\n";
	} 
?>  
  </ul>
  Files added in MIB directory : 
  <ul>
 <?php
	foreach ($this->fileList as $file)
	{
		echo '<li>'.$file . "</li>\n";
	}
 ?>
  </ul>
   <p>
	Add a mib FILE (NOT IMPLEMENTED) :
	<form id="file-form" action="#" method="POST">
		<input type="file" id="mib-select" name="mibs[]" multiple/>
		<button type="submit" id="upload-button">Upload</button>
	</form>
	</p>
  <br><br>
  
</div>

<script type='text/javascript'>
mibfileHelper='/icingaweb2/trapdirector/status/mib';

// TODO : put function in a js (duplicate from add.phtml)
function displayWarning(message)
{
	// for now
	alert(message);
}
function displayOK(message)
{
	// for now
	alert(message);
}

function updateMIB()
{
	$("#id_apply_mib").prop("disabled",true);
	
	//$("#id_animate_apply_mib").addClass("spinner");
	$("#id_animate_apply_mib").css("animation","spin 2s linear infinite");	
	$("#id_animate_apply_mib").show();

	$.ajax({
			url: mibfileHelper,
			async: true,
			dataType: "json",
			type: "POST",
			data: 
			{
				"action"	: 	"update_mib_db"
			},
	        success: function (data) 
			{
				$("#id_apply_mib").prop("disabled",false);
				$("#id_animate_apply_mib").css("animation","none");	
				$("#id_animate_apply_mib").hide();	
				if (data.status == "OK") 
				{
					displayOK("Done");
				} 
				else 
				{
					displayWarning("Error : "+data.status);		
				}
			
			},
			error: function (data)
			{
				$("#id_apply_mib").prop("disabled",false);
				$("#id_animate_apply_mib").css("animation","none");	
				$("#id_animate_apply_mib").hide();				
				
				displayWarning ("Error" + data);
			}
	});		
	
	setTimeout(function(){

	}, 5000);
}

function add_mib_files()
{
	alert("Not Implemented");
}



</script>
