<div class="controls">
  <?= $tabs ?>
  <h1>Mib Management</h1>
</div>

<div class="content">
	<h2>MIB Database</h2>
	<ul>
	<li>Traps in database : <?= $this->mibDbCountTrap ?></li>
	<li>Objects in database : <?= $this->mibDbCount ?></li> 
	
	</ul>
	<br>
	<button type="button" onclick="updateMIB()">Update MIB Database</button>
	Note : can take very long time
   <h2>snmptranslate</h2>
  
  Binary (<?= $this->snmptranslate_bin ?>) : 
	<span style="background-color:<? 
		if ($this->snmptranslate_state == 'warn') echo "#FFE555";
		else echo "#00D500"
	?>; font-weight:bold;"> 
		<?= $this->snmptranslate ?> </span>
		
  <h2>Mib directories</h2>
  Directories where mibs are found (configured in module configuration) : 
  <ul>
<?php 
	//print_r($this->dirArray);
	foreach($this->dirArray as $key=>$dir) 
	{ 
		echo '<li>'.$dir.' : (aprox. '.exec('cat '.$dir.'/*  | grep "NOTIFICATION-TYPE" | wc -l 2>/dev/null');
		echo " traps defined)</li>\n";
	} 
?>
  </ul>  
		<p>
		Add a mib FILE (NOT IMPLEMENTED) :
		<form id="file-form" action="#" method="POST">
			<input type="file" id="mib-select" name="mibs[]" multiple/>
			<button type="submit" id="upload-button">Upload</button>
		</form>
	</p>
  <br><br>
  
  Files added in MIB directory : 
  <ul>
 <?php
	foreach ($this->fileList as $file)
	{
		echo '<li>'.$file . "</li>\n";
	}
 ?>
  </ul>

  
</div>

<script type='text/javascript'>
mibfileHelper='/icingaweb2/trapdirector/helper/addmibfiles';

// TODO : put function in a js (duplicate from add.phtml)
function displayWarning(message)
{
	// for now
	alert(message);
}
function displayOK(message)
{
	// for now
	alert(message);
}

function updateMIB()
{
	alert("Not Implemented");
}

function add_mib_files()
{
	alert("Not Implemented");
}

$(function() {
	return;
});

</script>
