<div class="controls">
  <?= /** @var \Icinga\Module\Trapdirector\Controllers\StatusController $this */ $this->tabs ?>
  <h1>Web interface configuration</h1>
</div>

<?php use Icinga\Web\Url; ?>

<div class="content">
  <h2>Tables</h2>
   <form action="<?= Url::fromRequest() ?>" method="post">
    Maximum rows in table before paging :  <input type="text" id="input_max_rows" name="max_rows" maxlength="4" style="width:4em;"
  value="<?= $this->maxRows ?>" /> <input type="submit" name="row_update" value="update"> <br><br>
  		
  	</form>
  	<hr>
   <h2>Categories</h2>
	<br>
	
	<form action="<?= Url::fromRequest() ?>" method="post">
	Add category : <input type="text" name="add_category" maxlength="40"  size=30>
	 <input type="submit" name="add_category_submit" value="Add">
	</form>
	
	<br>
	 
	<table>
		<tr align = "left">
			<th>Index</th>
			<th>Name</th>

		</tr>
<?php 
    foreach ($this->categories as $index => $value)
    {
        echo '<tr>';
        echo '<td>' . $index . '</td>';
        if ($index == 0)
        {
            echo '<td>'.$value.'</td>';
        }
        else
        { 
            echo '<td> <input type="text" id="catName_'.$index.'" value="' . $value . '"></td>';
            echo '<td><button type="button" onclick=\'click_button_category("rename",'. $index .', "#catName_'.$index.'")\'>Rename</button> </td>';
            echo '<td><button type="button" onclick=\'click_button_category("delete",'. $index .', "#catName_'.$index.'")\'>Delete</button> </td>';
            
        }
        
        echo '</tr>';
    }
?>				
	</table>
	
</div>

<script type='text/javascript'>
function displayWarning(message)
{
	$("#footer > #notifications").html('<li class="error">'+message+'</li>');
	//alert(message);
}
function displayOK(message)
{
	$("#footer > #notifications").html('<li class="success">'+message+'</li>');
}

function click_button_category(type,index,newname)
{
	newname = $(newname).val();
	$.ajax({
			url: '<?= Url::fromRequest() ?>',
			async: true,
			dataType: "json",
			type: "POST",
			data: 
			{
				"type"		: 	type,
				"index"		:	index,
				"newname"	: newname
			},
	        success: function (data) 
			{
				//alert(data.status);
				if (data.status == "OK") 
				{
					displayOK("Done");
					if (type == 'delete') 
					{
						location.reload();
						return false;
					}
				} 
				else 
				{
					displayWarning("Error : "+data.status);		
				}
			},
			error: function (data)
			{
				displayWarning ("error" + data);
			}
	});	
}


<?php 

    if ($this->setError != '')
    {
        echo 'displayWarning("Error : ' . $this->setError  . '");';
    }
    else if  ($this->setOKMsg != '')
    {
        echo 'displayOK("' . $this->setOKMsg  . '");';
    }       
?>

$(function() {
	return;
});

</script>